# Generated by Django 4.1.1 on 2023-05-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_is_varified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_varified',
            new_name='is_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
